<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-B8A8UDTS" failures="1" tests="6" name="testlayerlogin.GuestAccountTest" time="17.884" errors="0" timestamp="2023-03-08T00:30:18 EST" skipped="0">
  <testcase classname="testlayerlogin.GuestAccountTest" name="validDealsStore" time="0.893">
    <failure message="expected [Amazon.ca - Today&#039;s Deals] but found [Help - Amazon Customer Service]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Amazon.ca - Today's Deals] but found [Help - Amazon Customer Service]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testlayerlogin.GuestAccountTest.validDealsStore(GuestAccountTest.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validDealsStore -->
  <system-out/>
  <testcase classname="testlayerlogin.GuestAccountTest" name="validBestSellers" time="1.566"/>
  <system-out/>
  <testcase classname="testlayerlogin.GuestAccountTest" name="validSearchbar" time="0.422"/>
  <system-out/>
  <testcase classname="testlayerlogin.GuestAccountTest" name="validSearchoption" time="2.018"/>
  <system-out/>
  <testcase classname="testlayerlogin.GuestAccountTest" name="validSelection" time="6.130"/>
  <system-out/>
  <testcase classname="testlayerlogin.GuestAccountTest" name="validProceedtocheckout" time="6.855"/>
  <system-out/>
</testsuite> <!-- testlayerlogin.GuestAccountTest -->
